sudo: required
services:
  - docker

before_install:
  - docker build -t wheresmycookie/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run wheresmycookie/multi-docker-test npm test -- --coverage

after_success:
  - docker build -t wheresmycookie/udemy-multi-client ./client
  - docker build -t wheresmycookie/udemy-multi-nginx ./nginx
  - docker build -t wheresmycookie/udemy-multi-server ./server
  - docker build -t wheresmycookie/udemy-multi-worker ./worker
  # Docker Login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push those images to dockerhub
  - docker push wheresmycookie/udemy-multi-client
  - docker push wheresmycookie/udemy-multi-nginx
  - docker push wheresmycookie/udemy-multi-server
  - docker push wheresmycookie/udemy-multi-worker
